site_name: Cloud Cost Handbook
site_url: http://handbook.vantage.sh
theme:
  name: material
  features:
    - navigation.sections
extra:
  generator: false

nav:
  - 'Overview' : 'index.md'
  - 'Leaderboard': 'leaderboard.md'
  - 'General Concepts': 
    - 'Your Monthly Bill': 'aws/concepts/bill.md'
    - 'Regions' : 'aws/concepts/regions.md'
    - 'Credits': 'aws/concepts/credits.md'
    - 'Budgets': 'aws/concepts/budgets.md'
    - 'Rightsizing': 'aws/concepts/rightsizing.md'
    - 'Savings Plans' : 'aws/concepts/savings-plans.md'
    - 'Reserved Instances' : 'aws/concepts/reserved-instances.md'

  - 'AWS Services':
    - 'EC2': 'aws/services/ec2-pricing.md'
    - 'RDS': 'aws/services/rds-pricing.md'
    - 'S3': 'aws/services/s3-pricing.md'
    - 'EBS': 'aws/services/ebs-pricing.md'
    - 'EC2-Other': 'aws/services/ec2-other-pricing.md'
    - 'Fargate': 'aws/services/fargate-pricing.md'
    - 'CloudWatch': 'aws/services/cloudwatch-pricing.md'
    - 'CloudFront': 'aws/services/cloudfront-pricing.md'
    - 'ElastiCache': 'aws/services/elasticache-pricing.md'
    - 'ECR': 'aws/services/ecr-pricing.md'
  
google_analytics:
  - G-TEYTN5V029
  - auto